name: Continuous Integration

on:
  push:
    branches:
      - main
      - actions-*
    tags:
      - v*
  pull_request:
    branches-ignore:
      - actions-*
  workflow_dispatch:

env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3

jobs:
  build:
    name: build ruby-${{ matrix.ruby }} ${{ matrix.appraisal }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby: "ruby"
            standardrb: true
          - ruby: "3.2"
            appraisal: "sidekiq_8"
          - ruby: "2.7"
            appraisal: "sidekiq_7"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby}}
    - name: Set Appraisal bundle
      if: matrix.appraisal != ''
      run: |
        echo "using gemfile gemfiles/${{ matrix.appraisal }}.gemfile"
        bundle config set gemfile "gemfiles/${{ matrix.appraisal }}.gemfile"
    - name: Install gems
      run: |
        bundle install
    - name: Run Tests
      run: bundle exec rake
    - name: standardrb
      if: matrix.standardrb
      run:  bundle exec standardrb
